export const ASSET_LOAD_STARTED = "ASSET_LOAD_STARTED";
export const ASSET_LOAD_COMPLETED = "ASSET_LOAD_COMPLETED";
export const ASSET_ADD_DATA_REQUEST = "ASSET_ADD_DATA_REQUEST";
export const ASSET_ADD_DATA_ADDED = "ASSET_ADD_DATA_ADDED";